### ISSUE TITLE
Pressing 'g' key to revalidate

### ISSUE THREAD

**Issue by lassik** [arthurgleckler/validate-html#4]
In `compilation-mode` the `g` key is bound to `recompile` and usually causes the last task to be repeated (e.g. the last `make` command). Currently pressing `g` in the validation results buffer causes an unrelated command to be rerun (specifically, the last command given to M-x `compile`). Could `g` be made to re-validate the last HTML file instead?

**Comment by arthurgleckler** [comment]
It's on my list, thank you.  Contributions welcome.

**Comment by lassik** [comment]
Implemented in b53e35d.
